from config import RPC_URL, POOL_ID, AMOUNT_IN, SLIPPAGE
# ... שאר הקוד נשאר כמו קודם ... 

🔄 Swapping 0.001 SOL to SEMD...
✅ Swap sent! Tx signature: <חתימת טרנזקציה>
🕒 Waiting 60 seconds before next swap... 

❌ Swap failed: <פירוט השגיאה> 